### ISSUE TITLE
How to use combine for text entered into a SwiftUI Textfield?

### ISSUE THREAD

**Issue by dirk68-fu** [heckj/swiftui-notes#10]
Hi,

first: Great document. The most complete and understandable text explaining the combine framework! Keep up the good work!

In one of the WWDC session (https://developer.apple.com/videos/play/wwdc2019/712/ starting at 11m 50s) the presenter explains how to process the stream of text coming from a TextField.
Unfortunately the presentation does this all on slides, there is never any concrete code or a demo.

For your "Patterns" section: How would you do this using a TextField from SwiftUI?

I found some examples using PassthroughSubject, but ideally there should be an easier way to subscribe to text changes from a TextField.

**Comment by heckj** [comment]
I'll definitely show using a textfield getting updates within the patterns - both with SwiftUI and with UIKit. I might pass on AppKit for starters though, since I'm not yet running the beta on the Mac

**Comment by dirk68-fu** [comment]
Perhaps my question was not clear. I was asking about using the changes of a Textfield as source for a pipeline, like shown in the WWDC video.

**Comment by heckj** [comment]
I think I understand - The current proposed method based on what I can find in apple's docs is leveraging the NSNotificationCenter for all UIKit updates, and then using that as the publisher to which you can react. Casey Liss even has some sample bits out there (he's not a fan of using NSNoticationCenter in this way, and I can't say I blame him here-  https://www.caseyliss.com/2019/6/18/quick-notes-on-yesterdays-post) , as does @avdlee in his playground at https://github.com/AvdLee/CombineSwiftPlayground. There's also something of an example at https://github.com/tailec/CombineExamples if you want to dig around a bit in that code.

I need to sit down and make it work for myself in my own samples, and I intend to include something like this, as its clearly a pattern folks would like to use.

**Comment by dirk68-fu** [comment]
Very interesting links. Thank you for sharing them. Though they all use UIKit. I wanted to know the easiest way to get a publisher from a SwiftUI TextField.

Shouldn't this be as easy as calling a method like textfield.publisher(...). Or do I miss something.

**Comment by heckj** [comment]
I haven't looked at depth into SwiftUI to really have a solid answer yet, but in perusing the documentation there's a closure that you can set up (at initialization) to be called when the contents are edited (https://developer.apple.com/documentation/swiftui/textfield/3338359-init), and there may also be a direct way to look for the property being modified, such as @Published property wrapper - but I'm getting quite a bit out ahead of anything I've tried to really know as yet. 

SwiftUI includes a number of publishers built into their views, but I'm not clear on what they are or their uses as yet.

**Comment by heckj** [comment]
It also appears that initializing TextFields can be bound to a model, so it may be more sensible (depending on how you're using it), to get a publisher from the model - I suspect it depends entirely on where the source of truth is for the TextField - such as `@State` or `@ObjectBinding`

**Comment by someoneAnyone** [comment]
Would something like [this swiftui project](https://github.com/someoneAnyone/URL-Validator/blob/master/URL%20Validator/ContentView.swift) help?

**Comment by dirk68-fu** [comment]
Thanks, that seems to contain the necessary code. I still have to remove the URL specific features though to extract the essence.

**Comment by dirk68-fu** [comment]
In the meantime I found a solution myself. The key to it was that `$property` of a `@Published` property is a Publisher itself:

```swift
import PlaygroundSupport
import SwiftUI
import Combine

PlaygroundPage.current.needsIndefiniteExecution = true


class TextEngine:ObservableObject{
    @Published var textInput = ""
    @Published var textOutput = ""
    private var worker:AnyCancellable? = nil
    
    init(){
        worker = $textInput.print("raw input")
            .debounce(for: 2, scheduler: RunLoop.main)
        .removeDuplicates{$0 == $1}
        .print("debounced and duplicates removed")
        .assign(to:\.textOutput, on:self)
    }
}

let engine = TextEngine()

struct LiveView:View {
    @ObservedObject var engine:TextEngine

    var body: some View {
        VStack{
            TextField("Enter text", text: $engine.textInput)
            .textFieldStyle(RoundedBorderTextFieldStyle())
            Text(engine.textOutput)
            Spacer()
        }.padding()
    }
}

let liveView = UIHostingController(rootView: LiveView(engine: engine).frame(width:770, height:400))
liveView.preferredContentSize = CGSize(width: 770, height: 1100)
PlaygroundPage.current.liveView = liveView
```

**Comment by heckj** [comment]
I've got a model/example now properly in place, as of the pr #25
