### ISSUE TITLE
Completion-aware publishers

### ISSUE THREAD

**Issue by dehesa** [heckj/swiftui-notes#108]
Hi Joseph,

I was wondering if there are "Completion-aware" operators in Combine, such as the ReactiveSwift or RxSwift `then` operator, which lets you start a new publisher once the upstream have finished successfully (in case of failure, the error will be forwarded downstream). Any ideas?

Combine do have `allSatisfy` which can be tweaked for that purpose, but I guess it will be better to have a specific Publisher and I don't know how to create custom Publishers yet :)

Keep up the great work!

**Comment by heckj** [comment]
Hi Marcos - 

Combine doesn't quite have the same "chaining promises" structure of the `then` operator from those systems, but in some cases it can act similarly. I find it awkward to do the more equiv of chaining promises (or one-shot async calls), but you *can* do it with Combine, using a combination of `Future` and either `flatMap` or `map` & `switchToLatest`. 

I have some of this exposed as a pattern in the work here, specifically the pattern [Sequencing operations with Combine](https://heckj.github.io/swiftui-notes/#patterns-sequencing-operations).

If you want to do some of the fancy "do these things in parallel and then wait for all to complete" kind of coordination, then `zip` can come in immensely useful as well.

**Comment by dehesa** [comment]
Thank you for taking the time. I did see that example, but you are actually chaining on the value and not in the completion. Which wouldn't work for publishers that just complete without sending values (for example).

In any case, I do have my answer. Thank you.

FYI, reading your SwiftUI-notes on the iPad (Safari to be exact) is maddening since every time I jump to another application (e.g. to take notes) the scroll position randomly changes.

**Comment by heckj** [comment]
thanks for the heads up with safari - i’ll see what i can do to help resolve that.

**Comment by heckj** [comment]
your absolutely correct about triggering on the value vs completion itself. you might be interested to look at the newer ObservableObjectPublisher ( https://heckj.github.io/swiftui-notes/#reference-observableobjectpublisher  ) which has a short of shim/workaround to this specific concept - it triggers with an output of ObservableObject.Output, which is type cast to Void. in the end it means you can get a sink to trigger, but it has no real info passed through to it - just that it happened. 

Probably not what you want to use if you’re looking for the moral equiv of a complex promise chain, but interesting detail none the less.

**Comment by dehesa** [comment]
It is interesting indeed, thank you.

I think I will go the *custom publisher* route, though. More like an "educational" experience than anything else. The [3 articles](https://www.cocoawithlove.com/blog/twenty-two-short-tests-of-combine-part-1.html) of Matt Gallagher explaining the shadow chain of subscriptions gave me an interesting understanding on Combine's internal usage that I am itching to apply ;)

**Comment by dehesa** [comment]
Hi @heckj,

I just wanted to follow up on this question I opened some weeks ago and mention that I ended up rolling my own `then` operator along with some other publishers/subscribers. Maybe you find them interesting or can give me feedback. You can find my them in [this Github repo](https://github.com/dehesa/Conbini) with a shoutout to your site ;)

Keep up the good work!
