### ISSUE TITLE
I see a blank screen.

### ISSUE THREAD

**Issue by UncleRic** [heckj/swiftui-notes#121]
I attempted to run your application; but only got:

> 2019-11-17 11:00:28.783593-0800 SwiftUI-Notes[12220:411888] Metal API Validation Enabled

**Comment by heckj** [comment]
hi @UncleRic - only the UIKit application will do anything, which is an alternate target - switch the target to the other application, and it should demo far more effectively. 

the first target is being used more to simply verify how Combine operated with a large bevy of unit tests - so there’s really nothing visual to see in either the simulator or a device with it. in the future, i’m planning on building out something based on SwiftUI, but haven’t yet made that jump.
