### ISSUE TITLE
Return resolved Future

### ISSUE THREAD

**Issue by mycroftcanner** [heckj/swiftui-notes#126]
It could be useful to explain how to return a resolved future...

I couln't find anywhere how to return a resolved or a failed future.

**Comment by mycroftcanner** [comment]
Is there a simpler way to do this then the following? :

```
return Future<T, Error> { promise in
            promise(.success(T()))
        }.eraseToAnyPublisher()
```

**Comment by heckj** [comment]
I think that pretty much strikes to the heart of it. By using the Future publisher in Combine, it will inherently be an asynchronous call, but will resolve pretty darn quickly if the underlying closure doesn't take much time.

**Comment by mycroftcanner** [comment]
I have been using this to return a failed publisher in a guard statement:

```
            return Fail<APIHandler, Error>(error: APIErrors.missingHandler).eraseToAnyPublisher()
```

**Comment by heckj** [comment]
I think that's a simpler and more direct way of achieving a cancelled pipeline
