### ISSUE TITLE
Collect byCount, byTime and byTimeOrCount examples

### ISSUE THREAD

**Issue by mycroftcanner** [heckj/swiftui-notes#130]
Couldn't find a single example for this in the book and on Google.

**Comment by heckj** [comment]
I'd planned to hit these when I started working through documenting the reducing operators (https://github.com/heckj/swiftui-notes/issues/88)

**Comment by heckj** [comment]
@mycroftcanner I have examples up and loaded now, merged with https://github.com/heckj/swiftui-notes/pull/156. I also noticed your StackOverflow question was while I was writing that segment and pushed an answer up there for you as well.
