### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by peterlondon1** [heckj/swiftui-notes#134]
1. This text:

“For example, there are a number of operators that have a similar operator prefixed with try”

should maybe be:

“For example, there are a number of operators that have a **matching** operator **with the same name prefixed with try, such as map and tryMap**"

2. This text:

“Figure 1. An exmample marble diagram”
should be:
“Figure 1. An **example** marble diagram”

3. This text:

“any pipelines created and full engaged”
should be:
“any pipelines created and **fully** engaged”

4. This text:

“The demand request is propogated up”
should be:
“The demand request is **propagated** up”

**Comment by peterlondon1** [comment]
too minor I think

**Comment by heckj** [comment]
thanks @peterlondon1, I think I just merged a change that fixes exactly that typo. Nothing too small, I appreciate the report!
