### ISSUE TITLE
Incorrect code example onreceive only works on statement not definitions

### ISSUE THREAD

**Issue by alexbbrown** [heckj/swiftui-notes#137]
“The onReceive function takes a closure”

The code example below shows something like

    Var x: View { Text() }.onReceive { } 

But declarations don’t work that way.  You need to attach on receive to the inner view

**Comment by heckj** [comment]
thanks @alexbbrown, ill get that updated. i need to make a full example for that, and when i originally wrote it, i didnt have Catalina to really work swiftui easily. no excuse now, just need to do it.
