### ISSUE TITLE
ASCII art should not wrap

### ISSUE THREAD

**Issue by Jean-Daniel** [heckj/swiftui-notes#16]
On small screens, the pipelines representation are not legible. I think these snippets should be made horizontally scrollable and not wrap.

![85A8D874-3151-421D-B989-DF75AAA80F97](https://user-images.githubusercontent.com/304649/60491274-b369b980-9ca8-11e9-9d83-565df96c0dd8.jpeg)

**Comment by heckj** [comment]
Yeah, I've seen the same - the asciidoc default output is limited in that respect, but I'll see what I can do there. I am planning on ultimately transitioning those to graphics images instead of ASCII art as well

**Comment by heckj** [comment]
will be replacing ascii art with diagrams:
- #77 
- #76
