### ISSUE TITLE
No Version string in epub document

### ISSUE THREAD

**Issue by dhoerl** [heckj/swiftui-notes#166]
I had 0.8 EPUB installed on an iPad. Downloaded 0.9, tried to launch it - but I think I got 0.8. Then I found there was no version string anywhere. I quit, retried again, got the latest release. 

It would just be nice to be able to tell quickly what version of the document is open. Thanks!

**Comment by heckj** [comment]
good point, i see what you mean!

i’m thinking something at the very beginning, under “About this book” as a decent location. would that help for your need?

**Comment by dhoerl** [comment]
Yes! And it’s not just for me, I’m just the first to note it. 😁

**Comment by heckj** [comment]
I've got a PR merged that puts some version information front and center! Next PDF and ePUB release will have it up front!
