### ISSUE TITLE
Confusing `promise` usage

### ISSUE THREAD

**Issue by dhoerl** [heckj/swiftui-notes#167]
In the section on Futures, the `promise` is called thusly:

```
if let err = err {
    promise(.failure(err))
}
promise(.success(someBoolean))
```

In this example the result is a non-optional and so does not need unwrapping. But having the promise called twice does not seem to me to be a good programming practice.

The `promise` block could have side effects, and calling it first with a failure, then a second time with the success, could be problematic in real code.

If for no other reason, changing it to `if ... } else { ...}` would not cause Combine noobies to ponder why this code was written this way.

I actually did write code that ran to verify that in fact promise gets called twice (although the subscriber just gets one completion) - I was unsure if I was missing some obscure feature of Combine.

**Comment by heckj** [comment]
yep, you’re very right. in fact i spotted that yesterday while i was working on a variant project - i’ll get it updates to be a better example
