### ISSUE TITLE
Typo Error in Combine notes

### ISSUE THREAD

**Issue by nanujogi** [heckj/swiftui-notes#17]
** original text **
To illustrate changing types within a pipeline, here is a short snippet thsat starts with a publisher that generates <Int>, <Never> and end with a subscription taking <String>, <Never>.

**correct text **
To illustrate changing types within a pipeline, here is a short snippet that starts with a publisher that generates <Int>, <Never> and end with a subscription taking <String>, <Never>.

![typo-error1](https://user-images.githubusercontent.com/20643880/60495561-a9f34800-9cce-11e9-8714-265cdd5864f0.jpg)

**2nd.**

**original text**
The interals of Combine are all driven by the subscriber. This is how Combine supports the concept of back pressure.

**correct text**
The internals of Combine are all driven by the subscriber. This is how Combine supports the concept of back pressure.

![typo-error2](https://user-images.githubusercontent.com/20643880/60496001-8d0b4480-9ccf-11e9-8f75-7d2840280833.jpg)

**Comment by heckj** [comment]
thank you! I think I've already caught the first in edits I'll be merging shortly, but I'll double check both of these
