### ISSUE TITLE
Enqueue async operations in a serial queue

### ISSUE THREAD

**Issue by anechaev** [heckj/swiftui-notes#170]
Is there a way to call async publishers sequentially? For example, consider this code using [Promises](https://github.com/google/promises/blob/master/g3doc/index.md#all): 
```
  let queue = DispatchQueue.init(label: "serialQueue")
  return all(on: queue, promiseA(), promiseB_calledAfterA(), promiseC_calledAfterB())
    .then { (a: Int, b: String, c: Int) in
      if a != c { throw MyError.error }
      return Promise(b)
    }
```
The `all` method calls the next operation only after the previous asynchronous operation is completed.

In Combine, publishers `CombineLatest` and `Zip` don't wait until async operations are completed. Is there a way to write similar code with Combine?

The problem I'm trying to solve is to get the value A, execute operation B, get value C. If A and C are not equal, throw an error, otherwise - return the result of operation B. All operations are asynchronous.
My current (ugly) solution is the following:
```
  let a = publisherA()
    .flatMap { a -> AnyPublisher<(Int, T), MyError> in
      return Publishers.Zip(
        Result<Int, MyError>.Publisher(a),
        publisherB)
        .eraseToAnyPublisher()
    }.flatMap { (a, result) -> AnyPublisher<(Int, T, Int), MyError> in
      return Publishers.Zip3(
        Result<Int, MyError>.Publisher(a),
        Result<T, MyError>.Publisher(result),
        publisherC()
      ).eraseToAnyPublisher()
    }.tryMap { (before, result, after) -> T in
      if before != after { throw MyError.error }
      return result
    }
```

**Comment by heckj** [comment]
That’s pretty close to how you’d need to do it with Combine. Your statement about zip is not, however, entirely accurate. while it doesn’t wait for a publisher to finish, it *does* wait for a value from a set of publishers, so it can act as a sync point. 

There’s an example of this at https://heckj.github.io/swiftui-notes/#patterns-sequencing-operations

however, you’re trying to use publishers as promises - basically promise chaining if i understand your goal from the question. Combine can sort of do that, but it’s awkward - so while you can achieve your goal with this framework, i’m not sure it’s really your best choice here.

**Comment by anechaev** [comment]
Thank you for confirming!
