### ISSUE TITLE
Compile-time crash

### ISSUE THREAD

**Issue by UncleRic** [heckj/swiftui-notes#171]
This happens when I attempt to build the code:

<img width="959" alt="Screen Shot 2019-12-28 at 12 12 20 PM" src="https://user-images.githubusercontent.com/862735/71549040-ac77e700-296b-11ea-8410-7195172ff9b7.png">

**Comment by UncleRic** [comment]
Other targets are okay.
Only UIKit-Combine

**Comment by heckj** [comment]
@UncleRic I'm seeing exactly the same thing - I haven't changed anything explicit except upgraded to Xcode 11.3 (and iOS 13.2.2/13.3 in the simulator), so I suspect this is related to missing something now required for IOS 13

The failure point is the same bootstrap location that fails when you're missing an entitlement or permission, although it's very unclear what's the causing the failure in this case.

**Comment by heckj** [comment]
Ah, found it.

The run scheme for the target had `ThreadSanitizer` enabled. That's triggering a bug in Xcode/Simulator that's causing the application to crash. I found some references to disabling this in StackOverflow, although I don't know how to reference a specific bug to track and share that info.

I'll update the project shortly with the updated scheme disabling the ThreadSanitizer. I do hope they get that resolved shortly - it is (normally) a wonderful tool (I run it all the time as a default), but if it's crashing the app, that's not getting us anywhere.
