### ISSUE TITLE
Please turn off right justification

### ISSUE THREAD

**Issue by philosopherdog** [heckj/swiftui-notes#175]
Can I suggest turning off right justification when publishing a book? 

This makes books especially hard to read especially on small screens. The html version does this correctly but epub and pdf do not.

**Comment by heckj** [comment]
thanks - i hadn’t noticed this specifically, but i’ll give it a look. i assume you’re speaking specifically of viewing on an iphone?

and did you find a difference in my docker-based generation and that version vs current for asciidoc? (i recall earlier you mentioning you were installing from gem and running everything locally)

-joe

**Comment by philosopherdog** [comment]
Hi, I didn't try the docker install. I was looking at asciidoctor and I think you can setup the way it renders justification. Not sure though I didn't look too deeply at it.

**Comment by heckj** [comment]
@philosopherdog 👋 I was doing some digging in this topic, but unable to find details on how to generally set (or unset) right justification. Do you have any references in the docs to what you were thinking about here?

**Comment by heckj** [comment]
with the update releases just coming out, I've double checked and verified it's rendering as expected on iphones and small devices - so closing this. If there's something specific you're asking about changing, let me know
