### ISSUE TITLE
Publishers.Just was removed from Beta 3

### ISSUE THREAD

**Issue by dirk68-fu** [heckj/swiftui-notes#18]
`Publishers.Just` seems to have been removed from Beta 3 and even the corresponding [developer docs](https://developer.apple.com/documentation/combine/publishers/just) are missing.

**Comment by heckj** [comment]
Heh, yes, you are quite correct. I suspect a good replacement for most of the example use cases I've seen is Publishers.Once or Publisher.Optional. It will be interesting to see if it makes a come-back in the next beta, just as tryCatch did (it disappeared for Beta2, but reappeared in Beta3)

**Comment by heckj** [comment]
Ah, it looks like `Just` and `Future` are no longer prefixed with Publishers, but are still included. They're just outside of the generic Publishers enumeration. This reverts them back to more of where they were in beta1, but they're both still available.

**Comment by heckj** [comment]
The PR https://github.com/heckj/swiftui-notes/pull/19 updates to match the new locations and code samples
