### ISSUE TITLE
Typo under Figure 4

### ISSUE THREAD

**Issue by jcmourey** [heckj/swiftui-notes#197]
In legend under Figure 4, bullet 6:

A publisher may optionally send completion: receive(completion:). A completion can be either a normal termination, or may be a .failure completion, optionally propogating an error type. A pipeline that has been cancelled will not send any completions.
--

propogating -> propagating

**Comment by jcmourey** [comment]
Do a global search & replace for propogat* -> propagat*

**Comment by heckj** [comment]
thanks, I'll hit it!
