### ISSUE TITLE
A few typos I found

### ISSUE THREAD

**Issue by danwood** [heckj/swiftui-notes#202]
A few screenshots showing the typo and some context around the typo.

![Screen Shot 2020-04-01 at 4 05 04 PM](https://user-images.githubusercontent.com/207080/78269428-6c6e5600-74be-11ea-8f25-4c628f672bed.png)
![Screen Shot 2020-04-01 at 4 05 23 PM](https://user-images.githubusercontent.com/207080/78269434-6d9f8300-74be-11ea-86ed-c4ec3c574d2e.png)
![Screen Shot 2020-04-01 at 3 29 17 PM](https://user-images.githubusercontent.com/207080/78269436-6e381980-74be-11ea-9bdb-9952d159b15a.png)

**Comment by heckj** [comment]
thanks dan! On it!

**Comment by heckj** [comment]
fixed with #203
