### ISSUE TITLE
Future.Conduit leaks

### ISSUE THREAD

**Issue by makleso6** [heckj/swiftui-notes#206]
Hi! Thanks for great tutorial!
It seems that I'm not the only one find memory leak on async callback in Future
https://github.com/heckj/swiftui-notes/blob/master/UsingCombineTests/FuturePublisherTests.swift
https://forums.swift.org/t/combine-nested-publishers-leak/34779/14

What do you thing about it?

**Comment by heckj** [comment]
It's remarkably easy to accidentally invoke a capture (and leak) with the closure syntax right now, so being careful to explicitly capture can make a huge difference. It doesn't help with this case, but I've filed my own feedback, and recommend you do the same if it's biting you. Hopefully we'll see a tweak or update in a month or so (WWDC) with updates that resolve this.

**Comment by makleso6** [comment]
Thanks for feedback!
