### ISSUE TITLE
The question about using of AnyCancellable

### ISSUE THREAD

**Issue by liyong03** [heckj/swiftui-notes#210]
In the code of UIKit-Combine/GithubViewController.swift:
```
        let apiActivitySub = GithubAPI.networkActivityPublisher 
        .receive(on: RunLoop.main)
            .sink { doingSomethingNow in
                if (doingSomethingNow) {
                    self.activityIndicator.startAnimating()
                } else {
                    self.activityIndicator.stopAnimating()
                }
        }
        apiNetworkActivitySubscriber = AnyCancellable(apiActivitySub)
```
I don't understand, because `sink` already returns an `AnyCancellable`, why do you need to do `apiNetworkActivitySubscriber = AnyCancellable(apiActivitySub)`, why not directly assign the return value to `apiNetworkActivitySubscriber`?

**Comment by heckj** [comment]
In earlier versions of Combine, the `.sink` didn't return an object of type AnyCancellable. `.assign` did from early on, but the return type from sink didn't change until relatively recently. I didn't track when it *did* change, somewhere between iOS 13.1 and 13.4.

I'll simplify the code now that I can
