### ISSUE TITLE
Typo on Core Concepts Page

### ISSUE THREAD

**Issue by bendinwire** [heckj/swiftui-notes#219]
Typo here:
“Combine also goes farther than defining the **resut**, it”

Excerpt From
Using Combine
Joseph Heck
This material may be protected by copyright.

**Comment by heckj** [comment]
Thanks!

**Comment by heckj** [comment]
It looks like that's already been updated in the online content

**Comment by bendinwire** [comment]
Ah sorry for the dupe!

Joe
