### ISSUE TITLE
Details for the prepend operation is missing a "be"

### ISSUE THREAD

**Issue by abajwa** [heckj/swiftui-notes#233]
It's very minor but while reading through I noticed that under the "Prepend" operation details the last sentence in the paragraph below is missing a "be" before propagated.

The prepend operator is often used with single or sequence values that have a failure type of <Never>. If the publishers do accept a failure type, then all values will be published from the prefix publisher even if the suffix publisher receives a .failure completion before it is complete. Once the prefix publisher completes, the error will **be** propagated.

Thank you for this wonderful resource. I've really enjoyed learning about combine via your work!

**Comment by heckj** [comment]
Thanks @abajwa ! I'll get that updated, thanks for the spot!
