### ISSUE TITLE
Extra word in sentence

### ISSUE THREAD

**Issue by lrbrzezinski** [heckj/swiftui-notes#237]
**Describe the solution you'd like**

In the section **Developing with Combine**, the subsection **Reasoning about pipelines** contains an extra word (**_are_**) in the first sentence as highlighted in the copied text:

Reasoning about pipelines

When developing with Combine, there are two broader patterns of publishers **_are_** that frequently recur: expecting a publisher to return a single value and complete and expecting a publisher to return many values over time.

**Comment by heckj** [comment]
thank you!
