### ISSUE TITLE
add Future pattern

### ISSUE THREAD

**Issue by heckj** [heckj/swiftui-notes#24]
- example with Vision framework and camera data?
- link to references, extend on Promise/Future
- add tests
- set up example in code project

**Comment by chrisbnyc** [comment]
This would be great - on a related topic, I was hoping to find a good example of promise chaining for combining two serial asynchronous functions. Here's something I was working with as a potential use case:

- given a UIViewController with a MKMapView
- user pans the map, and I can store the region in a @Published var (e.g. `theRegion`)
- create a pipeline that takes `theRegion` and then does the following:
-- does an asynchronous function to find all PoIs in the region
-- does another asynchronous funtion to find distance for each PoI to the center of the map
-- finally updates UI by highlighting closest PoI

I can begin to grok the Future example you have but have not done enough promise chaining to extend it.  For a similar idea I have used a lot of OperationQueues and state management and it's a mess... hope this can help simplify that in the end.

A bonus would be showing how to execute the async options off the main thread.  

Thanks for this doc - so far I'm finding it much more helpful than Apple's docs.

**Comment by heckj** [comment]
hey @chrisbnyc - thanks for the suggestion.

I'm working in that direction right now, currently making edits and doing the learning for how to bind things to UIKit for UI updates there (the `@Published` part of that). 

I definitely had some ideas for chaining multiple async actions (with Publishers.Future) as a possible pattern example - I was thinking something with an Image processed by the Vision framework originally (taking the image from the camera or something), but your example idea is a darned good one too!

My initial experiments are showing that `@Published` variables have a lot of promise with UIKit for tracking some async state points, and along with PassthroughSubject make a pretty convenient way to trigger updates like this. 

The interesting quirk I'm trying to understand is `@Published` vs. a subject for ongoing update chains to an .assign() subscriber. It looks like using `@Published` with sink() and then doing something with the results is allowing error messages to cancel the subscription, and I haven't quite worked out how to use a subject as a subscriber as yet.

The same idea could be how to get continual updates from some UI element and then triggering one or more async processes from it that in turn make UI updates. I haven't quite figured out how to wire that up as yet so that it doesn't cancel the pipeline.
