### ISSUE TITLE
How to export and generate docset format？

### ISSUE THREAD

**Issue by iT-Boyer** [heckj/swiftui-notes#243]
**Describe the solution you'd like**
A clear and concise description of what you want to see added or updated.

Because of the instability of the network, I want to generate a docset file to use in dash App, so I can quickly preview relevant content locally.

**Comment by heckj** [comment]
I'm sorry, but the content is nowhere near the format that would be needed for a DocSet. It was hand created and curated, based loosely on the documentation that (at the time) Apple provided. 

That said, if you manually create the elements for the DocSet format, I imagine you could assemble what you're after, using the HTML that's already rendered. Kapeli has their details at https://kapeli.com/docsets#dashDocset.

That transformation isn't something that I'll be doing though.

**Comment by iT-Boyer** [comment]
I'm going to manually create the elements for the DocSet format, but there are errors when using the docker method to generate HTML format files。
```sh
$ cd swiftui-notes
$ docker run --rm -v $(pwd):/documents/ --name asciidoc-to-html heckj/docker-asciidoctor asciidoctor -v -t -D /documents/output -r ./docs/lib/google-analytics-docinfoprocessor.rb docs/using-combine-book.adoc
```
this log:
```
asciidoctor: WARNING: coreconcepts.adoc: line 299: no callout found for <1>
asciidoctor: WARNING: coreconcepts.adoc: line 300: no callout found for <2>
asciidoctor: WARNING: coreconcepts.adoc: line 301: no callout found for <3>
asciidoctor: WARNING: coreconcepts.adoc: line 302: no callout found for <4>
asciidoctor: WARNING: coreconcepts.adoc: line 304: no callout found for <5>
asciidoctor: WARNING: coreconcepts.adoc: line 305: no callout found for <6>
Input file: docs/using-combine-book.adoc
  Time to read and parse source: 0.72550
  Time to convert document: 0.46890
  Total time (read, parse and convert): 1.19440
```

**Comment by iT-Boyer** [comment]
thanks , i find the `output` dir in `swiftui-notes`。
