### ISSUE TITLE
add SwiftUI example pattern

### ISSUE THREAD

**Issue by heckj** [heckj/swiftui-notes#25]
- BindableObject publisher

**Comment by PaulWoodIII** [comment]
Its important to add some words on unidirectional data flow, and feedbacks / actions

There isn't much code in CombineFeedback thanks to generics. I think a minimalist version of State, Reducer and Actions / Feedbacks should be in this book to lay the ground works for people to move to other frameworks like CombineFeedback and whatever else is brewing elsewhere

https://github.com/sergdort/CombineFeedback
