### ISSUE TITLE
UIKit-Combine Black Screen while running

### ISSUE THREAD

**Issue by nanujogi** [heckj/swiftui-notes#38]
UIKit-Combine while Launching in iOS simulator shows Black Screen.
**Solution:** Create an new project copy paste ViewController.swift & Main.storyboard.
Compile & run in iOS simulator it works. Image attached for reference only.
![Black-Screen](https://user-images.githubusercontent.com/20643880/61167023-c2c4ee80-a555-11e9-8310-943c1e9109cb.jpg)

**Comment by heckj** [comment]
Thanks for the report @nanujogi - is this with the master branch currently? That is, commit [0a73b82](https://github.com/heckj/swiftui-notes/commit/0a73b826fd3a6dd380932e7dc2c41763ea93ecaa) or something earlier?

I suspect what you're seeing is a bug in Xcode 11 beta 3, I've seen the same effect a couple of times while doing this development on a couple of projects.

**Comment by nanujogi** [comment]
Yes its with master branch commit [0a73b82](https://github.com/heckj/swiftui-notes/commit/0a73b82) . Merged the recent commit [3ad911e](https://github.com/heckj/swiftui-notes/commit/3ad911e) still same problem of **Black Screen** so Its a **bug** in **Xcode 11 beta 3**.

**Comment by nanujogi** [comment]
Closing issue its **Xcode bug beta 3**

**Comment by peterlondon1** [comment]
I'm getting black screen with fresh clone of project, and using Xcode Version 11.3 (11C29)

**Comment by heckj** [comment]
Yep, sorry about that. I broke it while I was messing around with the ContentView to work out the correct layout for onReceive and didn't get it fixed earlier. It'll be fixed again in a sec - although honestly most of the good example work has been done against UIKit - the SwiftUI portion of this is horrifically anemic at the moment.

It'll be a focus to improve (it was the original reason to start this) after the review/edit pass that I'm going to tackle after the holidays.
