### ISSUE TITLE
Tiny change: Change instances of "strong" to "static"

### ISSUE THREAD

**Issue by erikt** [heckj/swiftui-notes#8]
This is a tiny issue I have with the introduction (in `docs/introduction.adoc`) and I also am aware of how these terms are not perfectly defined et cetera, but these lines make more sense if "strong" was replaced with "static": 

`... applying the strongly-typed nature of Swift to their solution.`

`Applying these concepts to a strongly typed language like swift ... `

Yes, Swift is "strongly typed", but it is also "statically typed" and, in my opinion, it is the static part that matters here.

**Comment by heckj** [comment]
Cool - good catch, thank you
